# Generated by Django 5.2.8 on 2025-11-28 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('profilePic', models.URLField(blank=True, null=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('seller', 'Seller')], default='user', max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
