# Generated by Django 5.2.8 on 2025-11-28 03:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('owner_id', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='kitchens/')),
                ('rating', models.FloatField(default=0)),
                ('total_orders', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('kitchen_name', models.CharField(max_length=120)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('delivery_time', models.IntegerField(db_index=True, default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)])),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('preparing', 'Preparing'), ('ontheway', 'On The Way'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='foods/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='food.kitchen')),
            ],
        ),
    ]
