# Generated by Django 5.2.8 on 2025-12-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
